name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Trunk Check
        uses: trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa # v2.0.0
        with:
          check-mode: payload
