name: Trunk Check
run-name: ${{ fromJSON(inputs.payload).checkWorkflowRunName }}
on:
  workflow_dispatch:
    inputs:
      payload:
        description: For invocation by Trunk Check
        required: false

permissions:
  contents: read

jobs:
  check:
    name: ${{ fromJSON(inputs.payload).checkJobName }}
    runs-on: ${{ fromJSON(inputs.payload).checkJobRunsOn }}
    concurrency:
      group: ${{ fromJSON(inputs.payload).concurrencyGroup }}
      cancel-in-progress: true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Trunk Check
        uses: trunk-io/trunk-action@04ba50e7658c81db7356da96657e6e77f220bfa3 # v1.3.1
        with:
          check-mode: payload
